#Stage1
FROM node:20-alpine AS  builder

#working directory for the app
WORKDIR /app

#
COPY package*.json ./

#Run the command to install the Lib to compile code 
RUN npm install

COPY . .

RUN npm run build


#Stage 2 

FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

#EXPOSE the port 
EXPOSE 5173

#Serve the app / Keep it running 
CMD ["serve", "-s", "dist", "-l", "5173"]                 
